travis:
  secure:
    BINSTAR_TOKEN: aI8E7gBk6o8FzqcSMNZ1CrvOzjRQWF1iFPv9qzqD6bn6/zT/u0Q64yey2wFyQJYjQ7BuCy5JqeNX/ilOPka2d/00POdVldLuA6nn0xsE3zGBxkSoP42m/2xo+93eNYcCbmuV/yBWOs0c1n85eWyryU4nJ1S8ysCCHAaZwIYHNBPH5dVtcud6I4b0WvEH/1Gbbz+oIcXfZhQR99bA8eQh24jRtQJqkGUQw85iTGtfP0mjL1OrdXxSvAqxYKvRkSGR2jrGCnXaVJYgWFKbToud3qCjQr51o9+iO090jgvFsgyRO4fqRc0Fsg06VO3I0Fi6ElGvXNNFhDA+dlRizOMkIMOA+3ZECAgGwm9TIlmB87r9IYVN1Rh+7ke/GhmZM2k28jaD8oW/vlWIwBSorPBNEsGviHIVBG9qMHpcss1Bx2tPIsy6lk1nRMdJ7/xDCIJxn/Yb6tmOEQzTkJoQRdYDxj5Ml5zQdaTzS0Hltpby5Cus3SZcWUvgOhUE3AHDq1P809gtpzqAnrkL7uJPLFxbE8pk1begjz+fuEV/EYKRxKT8ZOlp1bhHzn8j7of8TCqnh3YwaNkdH+32faIlQznKWtjSHLYu6/6QUR1Q4GUu812pgXFmZK/+mUREYn4yF0akfXHcIhKHIX+3Sp6ejj0mrqnaNy//VOjvNi4pVuzSwnM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
